### ISSUE TITLE
Support External Etcd

### ISSUE THREAD

**Issue by k** [weaveworks/wksctl#107]
It appears that eksctl only supports stacked etcd nodes. In production its in general better to decouple the two, but it would still be nice to benefit from wksctl's declarative YAML interface. 

This is a feature request to add to the Machine CRD support for declaring etcd nodes that would be provisioned via [etcdadm](https://github.com/kubernetes-sigs/etcdadm) or by kubeadm for now. For example, a simple 3 node cluster (master, etcd, and worker node) could be defined as:

```
apiVersion: v1
kind: List
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    name: master
    labels:
      set: master
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        public:
          address: 127.0.0.1
          port: 2222
        private:
          address: 172.17.0.2
          port: 22
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    name: etcd
    labels:
      set: etcd
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        public:
          address: 127.0.0.1
          port: 2223
        private:
          address: 172.17.0.3
          port: 22
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    name: worker-1
    labels:
      set: worker
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        public:
          address: 127.0.0.1
          port: 2225
        private:
          address: 172.17.0.5
          port: 22
```

Thoughts? There could perhaps be some other configuration that maps to etcdadm cli flags
