### ISSUE TITLE
Starting up Firekube as per instructions results in FATAL/ERROS

### ISSUE THREAD

**Issue by djcoder100** [weaveworks/wksctl#145]
Taking the fork from the repo as per README. instructions, and running ./setup.sh results in a failure on start up of the Firekube VMS.  This is running on a Ubuntu laptop.  

```
• Using git branch: master
• Using git remote: origin

• Found jk 0.3.0
• Found footloose 0.6.3
• Found ignite 0.5.5
• Found wksctl 0.8.1
• Creating footloose manifest
• Creating virtual machines
INFO[0000] Docker Image: chanwit/ignite-centos:7_pre2 present locally 
INFO[0000] Creating machine: firekube-node0 ...         
INFO[0002] Creating machine: firekube-node1 ...         
INFO[0005] Creating machine: firekube-node2 ...         
INFO[0008] Creating machine: firekube-node3 ...         
• Creating Cluster API manifests
• Generating haproxy.cfg
• Running external load-balancer
Error: No such container: haproxy
a540ba49198dd78d11fe121be2d2f779409f34f6daf70df92758c755a1452551
• Generating cluster.yaml
• Updating container images and git parameters
• Pushing initial cluster configuration
Username for 'https://github.com': ${user}
Password for 'https://${user}@github.com': 
Everything up-to-date
• Installing Kubernetes cluster

**ERRO[2020-03-04T22:37:34Z] machines[0].spec.versions.controlPlane: Invalid value: "": inconsistent controlPlane version, expected "1.14.1" 
ERRO[2020-03-04T22:37:34Z] machines[1].spec.versions.controlPlane: Invalid value: "": inconsistent controlPlane version, expected "1.14.1" 
ERRO[2020-03-04T22:37:34Z] machines[2].spec.versions.controlPlane: Invalid value: "": inconsistent controlPlane version, expected "1.14.1" 
FATA[2020-03-04T22:37:34Z] Error parsing manifest: /tmp/wkp343104114/machines.yaml failed validation, use --skip-validation to force the operation** 
```
The machines.yaml file is attached

```
cat /tmp/wkp343104114/machines.yaml
apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 172.18.0.2
          port: 22
        public:
          address: 127.0.0.1
          port: 2222
    versions:
      kubelet: 1.14.1
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-1
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 172.18.0.3
          port: 22
        public:
          address: 127.0.0.1
          port: 2223
    versions:
      kubelet: 1.14.1
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-2
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 172.18.0.4
          port: 22
        public:
          address: 127.0.0.1
          port: 2224
    versions:
      kubelet: 1.14.1
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-0
    namespace: weavek8sops
  spec:
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 172.18.0.5
          port: 22
        public:
          address: 127.0.0.1
          port: 2225
    versions:
      kubelet: 1.14.1
kind: List

```
