### ISSUE TITLE
support homebrew with goreleaser

### ISSUE THREAD

**Issue by dimitropoulos** [weaveworks/wksctl#15]
https://goreleaser.com/homebrew/

The code would look something like:

```yaml
brew:
  github:
    owner: weaveworks
    name: homebrew-tap
  commit_author:
    name: weaveworksbot
    email: team+gitbot@weave.works
  folder: Formula
  homepage: https://github.com/weaveworks/wksctl
  description: Open Source Weaveworks Kubernetes
```

### Acceptance criteria:
- [ ] tested on mac
- [ ] tested on linux
