### ISSUE TITLE
Flux memcached settings doesn't match namespace

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/wksctl#6]
The namespace setting for --memcached-hostname= is refernces the wrong namespace.  Instead of memcached.flux.svc.cluster.local it should be memcached.weavek8sops.svc.cluster.local

**Comment by bricef** [comment]
This issue persists in 0.8.2-alpha1. 

Command used to create cluster:

```bash
./tools/wksctl apply --git-branch master --git-deploy-key ~/.ssh/build-infra-git --git-url git@github.xyz.com:spg/build-platform.git --git-path domains/test-flux --ssh-key ~/.ssh/build-infra --namespace weave —verbose
```

Describing the flux agent deployment:

```yaml
kubectl describe --namespace weave deploy/flux                                                           badri/add-new-namespace ◼
Name:               flux
Namespace:          weave
CreationTimestamp:  Tue, 03 Dec 2019 13:58:03 -0800
Labels:             name=flux
Annotations:        deployment.kubernetes.io/revision: 1
                    kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"name":"flux","namespace":"weave"},...
Selector:           name=flux
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           name=flux
  Annotations:      prometheus.io.port: 3031
  Service Account:  flux
  Containers:
   flux:
    Image:      fluxcd/flux:1.13.3
    Port:       3030/TCP
    Host Port:  0/TCP
    Args:
      --ssh-keygen-dir=/var/fluxd/keygen
      --git-url=git@github.pie.apple.com:spg/build-platform.git
      --git-branch=master
      --git-poll-interval=30s
      --git-path="domains/test-flux"
      --memcached-hostname=memcached.flux.svc.cluster.local
      --memcached-service=memcached
      --listen-metrics=:3031
      --sync-garbage-collection
    Environment:  <none>
    Mounts:
      /etc/fluxd/ssh from git-key (ro)
      /var/fluxd/keygen from git-keygen (rw)
  Volumes:
   git-key:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  flux-git-deploy
    Optional:    false
   git-keygen:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   flux-9c6c75bc5 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  50s   deployment-controller  Scaled up replica set flux-9c6c75bc5 to 1
```

Note the incorrect ` --memcached-hostname=memcached.flux.svc.cluster.local` configuration
